version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      shopware:
        patterns:
          - "*shopware*"
      vitepress:
        patterns:
          - "*vitepress*"
      storybook:
        patterns:
          - "*storybook*"
      vite:
        patterns:
          - "*vite*"
      search:
        patterns:
          - "*instantsearch*"
          - "*algolia*"
      test:
        patterns:
          - "*test*"
      all-dependencies:
        patterns:
          - "*"